name: VMware
favicon: null
layout_spectrum: 0.74997
typography_spectrum: 0.75998
title: VMware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d6a8e'
    - '#c1ce2f'
    - '#51910d'
    - '#ffffff'
    - '#5d9bb3'
  brandStrength: 1
  lightness: 0.6681113010272384
  saturation: 1
  rhythmicContrast: 0.7452957811765373
purpose: []
